name: VR News Roundup
favicon: null
layout_spectrum: 0.7223416
typography_spectrum: 0.6087722
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.2187405
  lightness: 0.9964151
  saturation: 0.8395891
  rhythmicContrast: 0.09383048
purpose: []
